### ISSUE TITLE
Similarity to Modbus?

### ISSUE THREAD

**Issue by RoganDawes** [bmerry/sunsniff#1]
Hi,

Just wondering whether the data format bears any similarity to Modbus, since I have confirmed that the dongle is speaking modbus directly to the inverter over that RS232 port. That might provide some answers in terms of any unknown bytes, perhaps?

**Comment by bmerry** [comment]
It's one of the first things I looked at when I started digging into the protocol, but it didn't look at all similar. My guess is that the firmware on the dongle queries a known bunch of modbus registers then packages up the results in some other format for the network. It might be interesting to see whether the initial message from the server side tells it which modbus registers to query though. It's a fairly generic dongle so it seems plausible that that wouldn't be baked into the firmware.

**Comment by RoganDawes** [comment]
One technique I have used successfully in the past is to do a hexdump of the packets and print them one byte per line. Do the same with the serial data, then use diff (or meld, etc) to view the difference between dumps. Because it is one byte per line, there is no confusion with shifted offsets, etc, and the similarities are quite easy to spot.

**Comment by bmerry** [comment]
I took another look at the initial exchange when the connection is established. The server sends very little data to the client - certainly it doesn't look like enough to contain the modbus register IDs of all the registers to retrieve, although I can't figure out what the contents actually are (there is definitely some structure).

I'm going to close this for now, but let me know if you do manage to find some connection with the Modbus protocol.

**Comment by bmerry** [comment]
I've started adding Modbus support to sunsniff (because I've now installed my own RS485 connection) and there does appear to be some relationship. It's not a single relationship between the packet offsets and Modbus registers, but there do appear to be a couple of large blocks in the packet that correspond to contiguous sequences of registers. That will probably help with some reverse engineering (possibly in both directions).

**Comment by bmerry** [comment]
> It makes sense that they might be encapsulating modbus in another protocol. Obviously the wireless device needs to identify itself first, which doesn't fit into the modbus scheme (although technically they probably could have just queried registers that are not allocated to the inverter, I guess). And there may be WiFi dongle firmware updates etc built into the wrapper protocol.
> 
> Watching this with interest!

I haven't spotted any evidence that the wire protocol is related to the Modbus packet format (whether TCP or RTU), although I haven't looked further. My comment was just meant to indicate that there is a relationship between the positions that data occupies in packets and the Modbus register numbers, which makes me think that the dongle is making a few bulk register reads and dumping the responses into packets.

**Comment by RoganDawes** [comment]
Oh, I see. Interesting, nonetheless!
